version: '3'

services:
  app:
    build:
      context: node
      dockerfile: Dockerfile.prod
    networks:
      - docker_node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app_node
    expose:
      - "8080"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-desafio-node
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - docker_node-network
    ports:
      - "3306:3306"


  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    networks:
      - docker_node-network
    ports:
      - "8080:80"

networks:
  docker_node-network:
    driver: bridge