FROM node:15 AS builder

WORKDIR /usr/src/app
COPY . .


FROM node:15-alpine

WORKDIR /var/www
RUN rm -rf /var/www/html

COPY --from=builder /usr/src/app .
RUN chown -R root:root /var/www

RUN yarn

EXPOSE 8080
CMD ["node", "index.js"]